version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: my_database
      DATABASE_USER: my_username
      DATABASE_PASS: my_password
      DATABASE_URI: mongodb://localhost:27017
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_username
      MONGO_INITDB_ROOT_PASSWORD: my_database